// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pkg_load
void pkg_load();
RcppExport SEXP _neo4r_pkg_load() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    pkg_load();
    return R_NilValue;
END_RCPP
}
// pkg_unload
void pkg_unload();
RcppExport SEXP _neo4r_pkg_unload() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    pkg_unload();
    return R_NilValue;
END_RCPP
}
// db_connect
SEXP db_connect();
RcppExport SEXP _neo4r_db_connect() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(db_connect());
    return rcpp_result_gen;
END_RCPP
}
// db_disconnect
void db_disconnect(SEXP r_conn);
RcppExport SEXP _neo4r_db_disconnect(SEXP r_connSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type r_conn(r_connSEXP);
    db_disconnect(r_conn);
    return R_NilValue;
END_RCPP
}
// test_query
void test_query(SEXP r_conn);
RcppExport SEXP _neo4r_test_query(SEXP r_connSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type r_conn(r_connSEXP);
    test_query(r_conn);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neo4r_pkg_load", (DL_FUNC) &_neo4r_pkg_load, 0},
    {"_neo4r_pkg_unload", (DL_FUNC) &_neo4r_pkg_unload, 0},
    {"_neo4r_db_connect", (DL_FUNC) &_neo4r_db_connect, 0},
    {"_neo4r_db_disconnect", (DL_FUNC) &_neo4r_db_disconnect, 1},
    {"_neo4r_test_query", (DL_FUNC) &_neo4r_test_query, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_neo4r(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
