# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pkg_load <- function() {
    invisible(.Call(`_neo4r_pkg_load`))
}

pkg_unload <- function() {
    invisible(.Call(`_neo4r_pkg_unload`))
}

db_connect <- function() {
    .Call(`_neo4r_db_connect`)
}

db_disconnect <- function(r_conn) {
    invisible(.Call(`_neo4r_db_disconnect`, r_conn))
}

test_query <- function(r_conn) {
    invisible(.Call(`_neo4r_test_query`, r_conn))
}

