# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pkg_load <- function() {
    .Call(`_neo4r_pkg_load`)
}

db_connect <- function(rurl) {
    .Call(`_neo4r_db_connect`, rurl)
}

db_disconnect <- function(conn) {
    .Call(`_neo4r_db_disconnect`, conn)
}

